name: deploy-debian

on:  # workflow_dispatch
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CI: false

#    strategy:
#      matrix:
#        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
      with:
          path: learning
 #   - name: Use Node.js ${{ matrix.node-version }}
 #     uses: actions/setup-node@v2
 #     with:
 #       node-version: ${{ matrix.node-version }}
    - run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get -yq install jq npm build-essential || true
#        cd edumeet
#        cp server/config/config.example.js server/config/config.js
#        cp app/public/config/config.example.js app/public/config/config.js
#        touch server/config/config.yaml
#        cd app
#        yarn install
#        yarn build
#        cd ../server
#        cat <<< $(jq '.bundleDependencies += .dependencies' package.json) > package.json
#        yarn install
#        npm pack
#        VERSION=$(cat package.json | jq -r '.version')
       VERSION=${{github.sha}}
       DATE=$(date)
       mkdir -p /home/runner/package
       cd /home/runner/package
       mkdir DEBIAN
       mkdir -p usr/local/src/edumeet/server
       mkdir -p etc/systemd/system/
#       tar -xf /home/runner/work/***/***/***/server/***-server-$VERSION.tgz package/ 1>/dev/null 2>/dev/null || true
        mv package/* usr/local/src/edumeet/server/
        mv /home/runner/work/***/***/***/*.service etc/systemd/system/
        rm -rf package
        touch DEBIAN/md5sums
        touch DEBIAN/md5sums
        touch DEBIAN/control
 #       find . -type f ! -regex '.*.hg.*' ! -regex '.*?debian-binary.*' ! -regex '.*?DEBIAN.*' -printf '%P ' | xargs md5sum  1>/dev/null 2>/dev/null || true
        echo """Package: learning
        Version: $VERSION
        Maintainer: sd4v1d
        Section: admin
        Date : $DATE
        Architecture: amd64
        Priority: important
        Description: Multiparty web-meetings using mediasoup and WebRTC (develop branch)
        Depends: nodejs (>= 16), redis
        """ > DEBIAN/control
        echo """#!/bin/bash
        mkdir -p /etc/learning/
        systemctl daemon-reload
        systemctl enable learning
        echo "\n\nPlease visit https://github.com/sd4v1d/learning/tree/main for configuration details.\n\n"
        echo "\n\nAfter the configuration, you can start service with 'sudo systemctl start learning' command.\n\n"
        """ > DEBIAN/postinst
        chmod 775 DEBIAN/postinst
        cd ../
        dpkg-deb -Zgzip --build package
        mv /home/runner/package.deb /home/runner/learning-$VERSION.deb
    - name : Release Package
      uses: actions/upload-artifact@v2
      with:
        name: learning-$VERSION
        path: "/home/runner/learning-$VERSION.deb"
