name: deploy-debian

on:  # workflow_dispatch
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CI: false

#    strategy:
#      matrix:
#        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
      with:
          path: learning
 #   - name: Use Node.js ${{ matrix.node-version }}
 #     uses: actions/setup-node@v2
 #     with:
 #       node-version: ${{ matrix.node-version }}
    - run: |
        VERSION=$( echo ${{ github.sha }} | head -c7)
        DATE=$(date)
        mkdir -p /home/runner/package
        cd /home/runner/package
        mkdir DEBIAN
        mkdir -p usr/local/src/learning
        mkdir -p etc/systemd/system/
        touch DEBIAN/md5sums
        touch DEBIAN/md5sums
        touch DEBIAN/control
        echo """Package: learning
        Version: 1.0-git-$VERSION
        Maintainer: sd4v1d
        Section: admin
        Date : $DATE
        Architecture: amd64
        Priority: important
        Description: Multiparty web-meetings using mediasoup and WebRTC (develop branch)
        Depends: nodejs (>= 16), redis
        """ > DEBIAN/control
        echo """#!/bin/bash
        mkdir -p /etc/learning/
        systemctl daemon-reload
        systemctl enable learning
        echo "\n\nPlease visit https://github.com/sd4v1d/learning/tree/main for configuration details.\n\n"
        echo "\n\nAfter the configuration, you can start service with 'sudo systemctl start learning' command.\n\n"
        """ > DEBIAN/postinst
        chmod 775 DEBIAN/postinst
        cd ../
        dpkg-deb -Zgzip --build package
        mv /home/runner/package.deb /home/runner/learning-$VERSION.deb
    - name : Release Package
      uses: actions/upload-artifact@v2
      with:
        name: learning
        path: "/home/runner/learning*.deb"
